.section .rodata

layer5_attn_norm_tensor_request:
	.ascii "blk.5.attn_norm.weight"
layer5_attn_norm_tensor_request_end:

layer5_attn_q_tensor_request:
	.ascii "blk.5.attn_q.weight"
layer5_attn_q_tensor_request_end:

layer5_attn_k_tensor_request:
	.ascii "blk.5.attn_k.weight"
layer5_attn_k_tensor_request_end:

layer5_attn_v_tensor_request:
	.ascii "blk.5.attn_v.weight"
layer5_attn_v_tensor_request_end:

layer5_attn_output_tensor_request:
	.ascii "blk.5.attn_output.weight"
layer5_attn_output_tensor_request_end:

layer5_ffn_norm_tensor_request:
	.ascii "blk.5.ffn_norm.weight"
layer5_ffn_norm_tensor_request_end:
