.section .rodata

layer4_attn_norm_tensor_request:
	.ascii "blk.4.attn_norm.weight"
layer4_attn_norm_tensor_request_end:

layer4_attn_q_tensor_request:
	.ascii "blk.4.attn_q.weight"
layer4_attn_q_tensor_request_end:

layer4_attn_k_tensor_request:
	.ascii "blk.4.attn_k.weight"
layer4_attn_k_tensor_request_end:

layer4_attn_v_tensor_request:
	.ascii "blk.4.attn_v.weight"
layer4_attn_v_tensor_request_end:

layer4_attn_output_tensor_request:
	.ascii "blk.4.attn_output.weight"
layer4_attn_output_tensor_request_end:

layer4_ffn_norm_tensor_request:
	.ascii "blk.4.ffn_norm.weight"
layer4_ffn_norm_tensor_request_end:

layer4_ffn_gate_tensor_request:
	.ascii "blk.4.ffn_gate.weight"
layer4_ffn_gate_tensor_request_end:

layer4_ffn_up_tensor_request:
	.ascii "blk.4.ffn_up.weight"
layer4_ffn_up_tensor_request_end:

layer4_ffn_down_tensor_request:
	.ascii "blk.4.ffn_down.weight"
layer4_ffn_down_tensor_request_end:
