.section .rodata

layer3_attn_norm_tensor_found_text:
	.ascii "layer3_attn_norm_tensor_found: "
layer3_attn_norm_tensor_found_text_end:

layer3_attn_norm_tensor_n_dimensions_text:
	.ascii "layer3_attn_norm_tensor_n_dimensions: "
layer3_attn_norm_tensor_n_dimensions_text_end:

layer3_attn_norm_tensor_dim0_text:
	.ascii "layer3_attn_norm_tensor_dim0: "
layer3_attn_norm_tensor_dim0_text_end:

layer3_attn_norm_tensor_ggml_type_text:
	.ascii "layer3_attn_norm_tensor_ggml_type: "
layer3_attn_norm_tensor_ggml_type_text_end:

layer3_attn_norm_tensor_offset_text:
	.ascii "layer3_attn_norm_tensor_offset: "
layer3_attn_norm_tensor_offset_text_end:
