.section .rodata

layer3_attn_norm_tensor_request:
	.ascii "blk.3.attn_norm.weight"
layer3_attn_norm_tensor_request_end:

layer3_attn_q_tensor_request:
	.ascii "blk.3.attn_q.weight"
layer3_attn_q_tensor_request_end:

layer3_attn_k_tensor_request:
	.ascii "blk.3.attn_k.weight"
layer3_attn_k_tensor_request_end:

layer3_attn_v_tensor_request:
	.ascii "blk.3.attn_v.weight"
layer3_attn_v_tensor_request_end:

layer3_attn_output_tensor_request:
	.ascii "blk.3.attn_output.weight"
layer3_attn_output_tensor_request_end:

layer3_ffn_norm_tensor_request:
	.ascii "blk.3.ffn_norm.weight"
layer3_ffn_norm_tensor_request_end:

layer3_ffn_gate_tensor_request:
	.ascii "blk.3.ffn_gate.weight"
layer3_ffn_gate_tensor_request_end:

layer3_ffn_up_tensor_request:
	.ascii "blk.3.ffn_up.weight"
layer3_ffn_up_tensor_request_end:
