
attn_norm_tensor_found_text:
	.ascii "attn_norm_tensor_found: "
attn_norm_tensor_found_text_end:

attn_norm_tensor_name_text:
	.ascii "attn_norm_tensor_name: "
attn_norm_tensor_name_text_end:

attn_norm_tensor_n_dimensions_text:
	.ascii "attn_norm_tensor_n_dimensions: "
attn_norm_tensor_n_dimensions_text_end:

attn_norm_tensor_dim0_text:
	.ascii "attn_norm_tensor_dim0: "
attn_norm_tensor_dim0_text_end:

attn_norm_tensor_dim1_text:
	.ascii "attn_norm_tensor_dim1: "
attn_norm_tensor_dim1_text_end:

attn_norm_tensor_dim2_text:
	.ascii "attn_norm_tensor_dim2: "
attn_norm_tensor_dim2_text_end:

attn_norm_tensor_dim3_text:
	.ascii "attn_norm_tensor_dim3: "
attn_norm_tensor_dim3_text_end:

attn_norm_tensor_ggml_type_text:
	.ascii "attn_norm_tensor_ggml_type: "
attn_norm_tensor_ggml_type_text_end:

attn_norm_tensor_offset_text:
	.ascii "attn_norm_tensor_offset: "
attn_norm_tensor_offset_text_end:

attn_q_tensor_found_text:
	.ascii "attn_q_tensor_found: "
attn_q_tensor_found_text_end:

attn_q_tensor_name_text:
	.ascii "attn_q_tensor_name: "
attn_q_tensor_name_text_end:

attn_q_tensor_n_dimensions_text:
	.ascii "attn_q_tensor_n_dimensions: "
attn_q_tensor_n_dimensions_text_end:

attn_q_tensor_dim0_text:
	.ascii "attn_q_tensor_dim0: "
attn_q_tensor_dim0_text_end:

attn_q_tensor_dim1_text:
	.ascii "attn_q_tensor_dim1: "
attn_q_tensor_dim1_text_end:

attn_q_tensor_dim2_text:
	.ascii "attn_q_tensor_dim2: "
attn_q_tensor_dim2_text_end:

attn_q_tensor_dim3_text:
	.ascii "attn_q_tensor_dim3: "
attn_q_tensor_dim3_text_end:

attn_q_tensor_ggml_type_text:
	.ascii "attn_q_tensor_ggml_type: "
attn_q_tensor_ggml_type_text_end:

attn_q_tensor_offset_text:
	.ascii "attn_q_tensor_offset: "
attn_q_tensor_offset_text_end:

attn_k_tensor_found_text:
	.ascii "attn_k_tensor_found: "
attn_k_tensor_found_text_end:

attn_k_tensor_name_text:
	.ascii "attn_k_tensor_name: "
attn_k_tensor_name_text_end:

attn_k_tensor_n_dimensions_text:
	.ascii "attn_k_tensor_n_dimensions: "
attn_k_tensor_n_dimensions_text_end:

attn_k_tensor_dim0_text:
	.ascii "attn_k_tensor_dim0: "
attn_k_tensor_dim0_text_end:

attn_k_tensor_dim1_text:
	.ascii "attn_k_tensor_dim1: "
attn_k_tensor_dim1_text_end:

attn_k_tensor_dim2_text:
	.ascii "attn_k_tensor_dim2: "
attn_k_tensor_dim2_text_end:

attn_k_tensor_dim3_text:
	.ascii "attn_k_tensor_dim3: "
attn_k_tensor_dim3_text_end:

attn_k_tensor_ggml_type_text:
	.ascii "attn_k_tensor_ggml_type: "
attn_k_tensor_ggml_type_text_end:

attn_k_tensor_offset_text:
	.ascii "attn_k_tensor_offset: "
attn_k_tensor_offset_text_end:

attn_v_tensor_found_text:
	.ascii "attn_v_tensor_found: "
attn_v_tensor_found_text_end:

attn_v_tensor_name_text:
	.ascii "attn_v_tensor_name: "
attn_v_tensor_name_text_end:

attn_v_tensor_n_dimensions_text:
	.ascii "attn_v_tensor_n_dimensions: "
attn_v_tensor_n_dimensions_text_end:

attn_v_tensor_dim0_text:
	.ascii "attn_v_tensor_dim0: "
attn_v_tensor_dim0_text_end:

attn_v_tensor_dim1_text:
	.ascii "attn_v_tensor_dim1: "
attn_v_tensor_dim1_text_end:

attn_v_tensor_dim2_text:
	.ascii "attn_v_tensor_dim2: "
attn_v_tensor_dim2_text_end:

attn_v_tensor_dim3_text:
	.ascii "attn_v_tensor_dim3: "
attn_v_tensor_dim3_text_end:

attn_v_tensor_ggml_type_text:
	.ascii "attn_v_tensor_ggml_type: "
attn_v_tensor_ggml_type_text_end:

attn_v_tensor_offset_text:
	.ascii "attn_v_tensor_offset: "
attn_v_tensor_offset_text_end:

attn_output_tensor_found_text:
	.ascii "attn_output_tensor_found: "
attn_output_tensor_found_text_end:

attn_output_tensor_name_text:
	.ascii "attn_output_tensor_name: "
attn_output_tensor_name_text_end:

attn_output_tensor_n_dimensions_text:
	.ascii "attn_output_tensor_n_dimensions: "
attn_output_tensor_n_dimensions_text_end:

attn_output_tensor_dim0_text:
	.ascii "attn_output_tensor_dim0: "
attn_output_tensor_dim0_text_end:

attn_output_tensor_dim1_text:
	.ascii "attn_output_tensor_dim1: "
attn_output_tensor_dim1_text_end:

attn_output_tensor_dim2_text:
	.ascii "attn_output_tensor_dim2: "
attn_output_tensor_dim2_text_end:

attn_output_tensor_dim3_text:
	.ascii "attn_output_tensor_dim3: "
attn_output_tensor_dim3_text_end:

attn_output_tensor_ggml_type_text:
	.ascii "attn_output_tensor_ggml_type: "
attn_output_tensor_ggml_type_text_end:

attn_output_tensor_offset_text:
	.ascii "attn_output_tensor_offset: "
attn_output_tensor_offset_text_end:

ffn_norm_tensor_found_text:
	.ascii "ffn_norm_tensor_found: "
ffn_norm_tensor_found_text_end:

ffn_norm_tensor_name_text:
	.ascii "ffn_norm_tensor_name: "
ffn_norm_tensor_name_text_end:

ffn_norm_tensor_n_dimensions_text:
	.ascii "ffn_norm_tensor_n_dimensions: "
ffn_norm_tensor_n_dimensions_text_end:

ffn_norm_tensor_dim0_text:
	.ascii "ffn_norm_tensor_dim0: "
ffn_norm_tensor_dim0_text_end:

ffn_norm_tensor_dim1_text:
	.ascii "ffn_norm_tensor_dim1: "
ffn_norm_tensor_dim1_text_end:

ffn_norm_tensor_dim2_text:
	.ascii "ffn_norm_tensor_dim2: "
ffn_norm_tensor_dim2_text_end:

ffn_norm_tensor_dim3_text:
	.ascii "ffn_norm_tensor_dim3: "
ffn_norm_tensor_dim3_text_end:

ffn_norm_tensor_ggml_type_text:
	.ascii "ffn_norm_tensor_ggml_type: "
ffn_norm_tensor_ggml_type_text_end:

ffn_norm_tensor_offset_text:
	.ascii "ffn_norm_tensor_offset: "
ffn_norm_tensor_offset_text_end:

ffn_gate_tensor_found_text:
	.ascii "ffn_gate_tensor_found: "
ffn_gate_tensor_found_text_end:

ffn_gate_tensor_name_text:
	.ascii "ffn_gate_tensor_name: "
ffn_gate_tensor_name_text_end:

ffn_gate_tensor_n_dimensions_text:
	.ascii "ffn_gate_tensor_n_dimensions: "
ffn_gate_tensor_n_dimensions_text_end:

ffn_gate_tensor_dim0_text:
	.ascii "ffn_gate_tensor_dim0: "
ffn_gate_tensor_dim0_text_end:

ffn_gate_tensor_dim1_text:
	.ascii "ffn_gate_tensor_dim1: "
ffn_gate_tensor_dim1_text_end:

ffn_gate_tensor_dim2_text:
	.ascii "ffn_gate_tensor_dim2: "
ffn_gate_tensor_dim2_text_end:

ffn_gate_tensor_dim3_text:
	.ascii "ffn_gate_tensor_dim3: "
ffn_gate_tensor_dim3_text_end:

ffn_gate_tensor_ggml_type_text:
	.ascii "ffn_gate_tensor_ggml_type: "
ffn_gate_tensor_ggml_type_text_end:

ffn_gate_tensor_offset_text:
	.ascii "ffn_gate_tensor_offset: "
ffn_gate_tensor_offset_text_end:

ffn_up_tensor_found_text:
	.ascii "ffn_up_tensor_found: "
ffn_up_tensor_found_text_end:

ffn_up_tensor_name_text:
	.ascii "ffn_up_tensor_name: "
ffn_up_tensor_name_text_end:

ffn_up_tensor_n_dimensions_text:
	.ascii "ffn_up_tensor_n_dimensions: "
ffn_up_tensor_n_dimensions_text_end:

ffn_up_tensor_dim0_text:
	.ascii "ffn_up_tensor_dim0: "
ffn_up_tensor_dim0_text_end:

ffn_up_tensor_dim1_text:
	.ascii "ffn_up_tensor_dim1: "
ffn_up_tensor_dim1_text_end:

ffn_up_tensor_dim2_text:
	.ascii "ffn_up_tensor_dim2: "
ffn_up_tensor_dim2_text_end:

ffn_up_tensor_dim3_text:
	.ascii "ffn_up_tensor_dim3: "
ffn_up_tensor_dim3_text_end:

ffn_up_tensor_ggml_type_text:
	.ascii "ffn_up_tensor_ggml_type: "
ffn_up_tensor_ggml_type_text_end:

ffn_up_tensor_offset_text:
	.ascii "ffn_up_tensor_offset: "
ffn_up_tensor_offset_text_end:

ffn_down_tensor_found_text:
	.ascii "ffn_down_tensor_found: "
ffn_down_tensor_found_text_end:

ffn_down_tensor_name_text:
	.ascii "ffn_down_tensor_name: "
ffn_down_tensor_name_text_end:

ffn_down_tensor_n_dimensions_text:
	.ascii "ffn_down_tensor_n_dimensions: "
ffn_down_tensor_n_dimensions_text_end:

ffn_down_tensor_dim0_text:
	.ascii "ffn_down_tensor_dim0: "
ffn_down_tensor_dim0_text_end:

ffn_down_tensor_dim1_text:
	.ascii "ffn_down_tensor_dim1: "
ffn_down_tensor_dim1_text_end:

ffn_down_tensor_dim2_text:
	.ascii "ffn_down_tensor_dim2: "
ffn_down_tensor_dim2_text_end:

ffn_down_tensor_dim3_text:
	.ascii "ffn_down_tensor_dim3: "
ffn_down_tensor_dim3_text_end:

ffn_down_tensor_ggml_type_text:
	.ascii "ffn_down_tensor_ggml_type: "
ffn_down_tensor_ggml_type_text_end:

ffn_down_tensor_offset_text:
	.ascii "ffn_down_tensor_offset: "
ffn_down_tensor_offset_text_end:
