.balign 8
layer6_attn_norm_tensor_slot:
layer6_attn_norm_tensor_found:
	.skip 8
layer6_attn_norm_tensor_name:
	.skip LAYER6_ATTN_NORM_TENSOR_NAME_CAP
layer6_attn_norm_tensor_n_dimensions:
	.skip 8
layer6_attn_norm_tensor_dim0:
	.skip 8
layer6_attn_norm_tensor_dim1:
	.skip 8
layer6_attn_norm_tensor_dim2:
	.skip 8
layer6_attn_norm_tensor_dim3:
	.skip 8
layer6_attn_norm_tensor_ggml_type:
	.skip 8
layer6_attn_norm_tensor_offset:
	.skip 8

.balign 8
layer6_attn_q_tensor_slot:
layer6_attn_q_tensor_found:
	.skip 8
layer6_attn_q_tensor_name:
	.skip LAYER6_ATTN_Q_TENSOR_NAME_CAP
layer6_attn_q_tensor_n_dimensions:
	.skip 8
layer6_attn_q_tensor_dim0:
	.skip 8
layer6_attn_q_tensor_dim1:
	.skip 8
layer6_attn_q_tensor_dim2:
	.skip 8
layer6_attn_q_tensor_dim3:
	.skip 8
layer6_attn_q_tensor_ggml_type:
	.skip 8
layer6_attn_q_tensor_offset:
	.skip 8
