.balign 8
layer4_attn_norm_tensor_slot:
layer4_attn_norm_tensor_found:
	.skip 8
layer4_attn_norm_tensor_name:
	.skip LAYER4_ATTN_NORM_TENSOR_NAME_CAP
layer4_attn_norm_tensor_n_dimensions:
	.skip 8
layer4_attn_norm_tensor_dim0:
	.skip 8
layer4_attn_norm_tensor_dim1:
	.skip 8
layer4_attn_norm_tensor_dim2:
	.skip 8
layer4_attn_norm_tensor_dim3:
	.skip 8
layer4_attn_norm_tensor_ggml_type:
	.skip 8
layer4_attn_norm_tensor_offset:
	.skip 8

.balign 8
layer4_attn_q_tensor_slot:
layer4_attn_q_tensor_found:
	.skip 8
layer4_attn_q_tensor_name:
	.skip LAYER4_ATTN_Q_TENSOR_NAME_CAP
layer4_attn_q_tensor_n_dimensions:
	.skip 8
layer4_attn_q_tensor_dim0:
	.skip 8
layer4_attn_q_tensor_dim1:
	.skip 8
layer4_attn_q_tensor_dim2:
	.skip 8
layer4_attn_q_tensor_dim3:
	.skip 8
layer4_attn_q_tensor_ggml_type:
	.skip 8
layer4_attn_q_tensor_offset:
	.skip 8

.balign 8
layer4_attn_k_tensor_slot:
layer4_attn_k_tensor_found:
	.skip 8
layer4_attn_k_tensor_name:
	.skip LAYER4_ATTN_K_TENSOR_NAME_CAP
layer4_attn_k_tensor_n_dimensions:
	.skip 8
layer4_attn_k_tensor_dim0:
	.skip 8
layer4_attn_k_tensor_dim1:
	.skip 8
layer4_attn_k_tensor_dim2:
	.skip 8
layer4_attn_k_tensor_dim3:
	.skip 8
layer4_attn_k_tensor_ggml_type:
	.skip 8
layer4_attn_k_tensor_offset:
	.skip 8

.balign 8
layer4_attn_v_tensor_slot:
layer4_attn_v_tensor_found:
	.skip 8
layer4_attn_v_tensor_name:
	.skip LAYER4_ATTN_V_TENSOR_NAME_CAP
layer4_attn_v_tensor_n_dimensions:
	.skip 8
layer4_attn_v_tensor_dim0:
	.skip 8
layer4_attn_v_tensor_dim1:
	.skip 8
layer4_attn_v_tensor_dim2:
	.skip 8
layer4_attn_v_tensor_dim3:
	.skip 8
layer4_attn_v_tensor_ggml_type:
	.skip 8
layer4_attn_v_tensor_offset:
	.skip 8

.balign 8
layer4_attn_output_tensor_slot:
layer4_attn_output_tensor_found:
	.skip 8
layer4_attn_output_tensor_name:
	.skip LAYER4_ATTN_OUTPUT_TENSOR_NAME_CAP
layer4_attn_output_tensor_n_dimensions:
	.skip 8
layer4_attn_output_tensor_dim0:
	.skip 8
layer4_attn_output_tensor_dim1:
	.skip 8
layer4_attn_output_tensor_dim2:
	.skip 8
layer4_attn_output_tensor_dim3:
	.skip 8
layer4_attn_output_tensor_ggml_type:
	.skip 8
layer4_attn_output_tensor_offset:
	.skip 8

.balign 8
layer4_ffn_norm_tensor_slot:
layer4_ffn_norm_tensor_found:
	.skip 8
layer4_ffn_norm_tensor_name:
	.skip LAYER4_FFN_NORM_TENSOR_NAME_CAP
layer4_ffn_norm_tensor_n_dimensions:
	.skip 8
layer4_ffn_norm_tensor_dim0:
	.skip 8
layer4_ffn_norm_tensor_dim1:
	.skip 8
layer4_ffn_norm_tensor_dim2:
	.skip 8
layer4_ffn_norm_tensor_dim3:
	.skip 8
layer4_ffn_norm_tensor_ggml_type:
	.skip 8
layer4_ffn_norm_tensor_offset:
	.skip 8
